-- MySQL Script generated by MySQL Workbench
-- Fri May  5 16:54:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema entrega
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema entrega
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `entrega` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `entrega` ;

-- -----------------------------------------------------
-- Table `entrega`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrega`.`articulos` (
  `id_articulo` INT NOT NULL AUTO_INCREMENT,
  `nombre_articulo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_articulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 105
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `entrega`.`entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrega`.`entregas` (
  `id_entrega` INT NOT NULL AUTO_INCREMENT,
  `fecha_entrega` DATE NULL DEFAULT NULL,
  `hora_entrega` TIME NULL DEFAULT NULL,
  `nombre_encargado` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `foto_articulo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_entrega`))
ENGINE = InnoDB
AUTO_INCREMENT = 108
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `entrega`.`detallearticulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrega`.`detallearticulos` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_entrega` INT NULL DEFAULT NULL,
  `id_articulo` INT NULL DEFAULT NULL,
  `descripcion_articulo` VARCHAR(200) NULL DEFAULT NULL,
  `foto_articulo` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `id_entrega` (`id_entrega` ASC) VISIBLE,
  INDEX `id_articulo` (`id_articulo` ASC) VISIBLE,
  CONSTRAINT `detallearticulos_ibfk_1`
    FOREIGN KEY (`id_entrega`)
    REFERENCES `entrega`.`entregas` (`id_entrega`),
  CONSTRAINT `detallearticulos_ibfk_2`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `entrega`.`articulos` (`id_articulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 215
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `entrega`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrega`.`personas` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre_persona` VARCHAR(100) NULL DEFAULT NULL,
  `firma_persona` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `entrega`.`detallepersonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrega`.`detallepersonas` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_entrega` INT NULL DEFAULT NULL,
  `id_persona` INT NULL DEFAULT NULL,
  `firma_encargado` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `id_entrega` (`id_entrega` ASC) VISIBLE,
  INDEX `id_persona` (`id_persona` ASC) VISIBLE,
  CONSTRAINT `detallepersonas_ibfk_1`
    FOREIGN KEY (`id_entrega`)
    REFERENCES `entrega`.`entregas` (`id_entrega`),
  CONSTRAINT `detallepersonas_ibfk_2`
    FOREIGN KEY (`id_persona`)
    REFERENCES `entrega`.`personas` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `entrega`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrega`.`failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `entrega`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrega`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `entrega`.`password_reset_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrega`.`password_reset_tokens` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `entrega`.`personal_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrega`.`personal_access_tokens` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `personal_access_tokens_token_unique` (`token` ASC) VISIBLE,
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type` ASC, `tokenable_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `entrega`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrega`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
